### ISSUE TITLE
[Feature Request] Sound Effect Downloads.

### ISSUE THREAD

**Issue by kucingpresto** [BEERproductions/EpidemicDL#1]
Hello! Thanks for your great script! it worked smoothly! But is it possible to add a function to download sound effects?

Thank you!

**Comment by ReComplexed** [comment]
Hi,
thanks for checking out my script!
I'm gonna look into it ASAP

**Comment by ReComplexed** [comment]
I added Sound Effect Downloads now.

Turned out it actually is pretty similar to normal Tracks.
The SFX Moods should work as well.

Tell me if you find any Issues!

- ReComplexed
